# Define your own admin routes here
mango_sylius_admin_order_message_send:
  path: admin/OrderMessage/{id}/send
  methods: [POST]
  defaults:
    _controller: MangoSylius\OrderCommentsPlugin\Controller\OrderMessageController:contactAction

