sylius_mailer:
  emails:
    order_mail:
      orderCommentEmail: 'Message regarding your order'
      template: "OrderMessage/orderEmailBody.html.twig"
    note_mail:
      orderCommentEmail: 'Create note on order'
      template: "OrderMessage/noteEmailBody.html.twig"
