sylius_resource:
  resources:
    mango_order_comments_plugin.orderMessage:
      classes:
        model: MangoSylius\OrderCommentsPlugin\Entity\OrderMessage
        form: MangoSylius\OrderCommentsPlugin\Form\Type\OrderMessageType

sylius_mailer:
  sender:
    name: '%env(SYLIUS_MAILER_SEND_FROM)%'
    address: '%env(SYLIUS_MAILER_SEND_FROM)%'

  emails:
    order_mail:
      subject: 'Message regarding your order'
      template: "OrderMessage/emailBody.html.twig"
