mango_sylius_admin_order_message_send:
    path: ordermessage/{orderId}/save
    methods: [POST]
    defaults:
        _controller: MangoSylius\OrderCommentsPlugin\Controller\OrderMessageController:save
