sylius_resource:
    resources:
        threebrs_order_comments_plugin.order_message:
            classes:
                model: ThreeBRS\OrderCommentsPlugin\Entity\OrderMessage
                form: ThreeBRS\OrderCommentsPlugin\Form\Type\OrderMessageType
