name: CI

on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                sylius_version: [ "1.10", "1.11" ]
                php_version: [ "8.0", "8.1" ]
                symfony_version: [ "5.4" ]

        name: PHP ${{ matrix.php_version }} - Sylius ${{ matrix.sylius_version }} - Symfony ${{ matrix.symfony_version }}

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: mysql
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        env:
            DATABASE_URL: "mysql://root:mysql@127.0.0.1:3306/sylius_test?charset=utf8mb4"
            APP_ENV: test
            APP_SECRET: ch4mb3r0f5ecr3ts
            MAILER_URL: "null://localhost"
            SYLIUS_API_AUTHORIZATION_HEADER: Authorization
            MESSENGER_TRANSPORT_DSN: "in-memory://"

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    extensions: intl, pdo_mysql, gd, exif, mbstring
                    coverage: none

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: '14'

            -   name: Install Yarn
                run: npm install -g yarn

            -   name: Require specific Sylius and Symfony version
                run: |
                    composer require "sylius/sylius:${{ matrix.sylius_version }}.*" --no-interaction --no-update --no-scripts
                    grep -o -E '"(symfony/[^"]+)"' composer.json | grep -v -E '(symfony/flex|symfony/webpack-encore-bundle|symfony/maker-bundle|symfony/panther|symfony/thanks|symfony/web-server-bundle)' | xargs printf '%s:${{ matrix.symfony_version }}.* ' | xargs composer require --no-interaction --no-update

            # PREFER DIST
            -   name: Composer install (prefer-dist)
                run: composer update --no-interaction --prefer-dist --no-plugins

            -   name: Install assets
                run: (cd tests/Application && bin/console assets:install --env=test -vvv)

            -   name: Yarn install
                run: yarn --cwd tests/Application install

            -   name: Yarn build
                run: GULP_ENV=prod yarn --cwd tests/Application build

            -   name: Create database
                run: (cd tests/Application && bin/console doctrine:database:create --if-not-exists --env=test -vvv)

            -   name: Create schema
                run: (cd tests/Application && bin/console doctrine:schema:update --force --complete --env=test -vvv)

            -   name: Cache warmup
                run: (cd tests/Application && bin/console cache:warmup --env=test -vvv)

            -   name: Generate JWT keypair
                run: (cd tests/Application && bin/console lexik:jwt:generate-keypair --skip-if-exists --no-interaction --env=test)

            -   name: Run PHPStan
                run: bin/phpstan.sh

            -   name: Run PHPUnit
                run: vendor/bin/phpunit

            -   name: Run Behat
                run: |
                    mkdir -p tests/Application/public/media/image
                    vendor/bin/behat --no-interaction
